liip_imagine:

  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public" #(%kernel.project_dir%/web for Symfony < 4.0.0)
        cache_prefix: "media/coche"

  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public" #(%kernel.project_dir%/web for Symfony < 4.0.0)

  driver:               gd
  cache:                default
  data_loader:          default
  default_image:        null
  controller:
    filter_action:         liip_imagine.controller:filterAction
    filter_runtime_action: liip_imagine.controller:filterRuntimeAction
  filter_sets:

    # Prototype
    game_avatar_current_char:
      quality:              100
      jpeg_quality:         ~
      png_compression_level:  ~
      png_compression_filter: ~
      animated:             false
      format:               ~
      cache:                ~
      data_loader:          ~
      default_image:        null
      filters:

        # Prototype
        name:                 []

      post_processors:

        # Prototype
        name:                 []