liip_imagine:
    filter_sets:
        current_character_front:
            quality: 100
            filters:
                thumbnail: { size: [133, 179], mode: outbound }
        page_character:
            quality: 100
            filters:
                thumbnail: { size: [178, 268], mode: outbound }
        capsule:
            quality: 100
            filters:
                thumbnail: { size: [], mode: outbound}