1:
  1:
    exp: 0
    bonus: 0
  2:
    exp: 0
    bonus: 0
  3:
    exp: 0
    bonus: 0
2:
  1:
    exp: 500
    bonus: 25
  2:
    exp: 1000
    bonus: 25
  3:
    exp: 500
    bonus: 25
3:
  1:
    exp: 1000
    bonus: 50
  2:
    exp: 2000
    bonus: 50
  3:
    exp: 1000
    bonus: 50
4:
  1:
    exp: 1500
    bonus: 75
  2:
    exp: 3000
    bonus: 75
  3:
    exp: 1500
    bonus: 75
5:
  1:
    exp: 2000
    bonus: 100
  2:
    exp: 4000
    bonus: 100
  3:
    exp: 2000
    bonus: 100
