characters:
  chibi_goku:
    name: "Chibi Gokû"
    alt: false
  bulma:
    name: "Bulma"
    alt: false
  tortue_geniale:
    name: "Tortue Géniale"
    alt: false
  yamcha:
    name: "Yamcha"
    alt: false